### PR TITLE
add support for new types

### PR DESCRIPTION
**Pull request by ghost**
According to https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.30.pdf (sec. 3.6) these keywords are now supported.

### CODE REVIEW

**Comment by beyondmarc** [comment]
Well spotted!
Would you mind propagating the changes to glsl440 & glsl450 syntax files?

Thanks!

**Comment by ghost** [comment]
Yes, I will check the other syntax files too, but it might take some time.

**Comment by ghost** [comment]
I have updated all the keywords I could see from version 4.20 to 4.60.

**Comment by ghost** [comment]
Personally I would prefer setting the **glslMemoryQual** keywords to **StorageClass** (like **const**).
Why are they of the **glslFunc** type?

**Comment by beyondmarc** [comment]
They should probably be StorageClass, as you say. I'm not sure why it was done this way, I inherited the original file, I just kept updating them :)

**Pull request merged**
